# 端口号
server:
  port: 8763
  servlet:
    context-path: /eureka-provider
# 服务注册与发现相关配置
eureka:
  client:
    # 服务注册地址
    serviceUrl:
      defaultZone: http://admin:123@localhost:8761/eureka/eureka
  server:
    enable-self-preservation: true
spring:
  security:
    user:
      name: admin
      password: 123